create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  is_complete boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.todos enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.todos to anon, authenticated;

drop policy if exists "Public can read todos" on public.todos;
create policy "Public can read todos"
on public.todos
for select
to anon, authenticated
using (true);

insert into public.todos (name, description, is_complete)
values
  ('Connect remote Supabase', 'Verify this Next.js app can read from the hosted project.', true),
  ('Create a demo table', 'Keep one simple table in the public schema for local verification.', true),
  ('Render rows on the home page', 'Use the server-side Supabase client to query todos.', false);
